# version attribute removed as it is obsolete
services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file:
      - server/.env
    depends_on: [mysql, mongo, redis]
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports: ["3306:3306"]
    volumes: [mysqldata:/var/lib/mysql]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongodata:/data/db]
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  mysqldata: {}
  mongodata: {}
